# Add these to your knowledge_base.py file

acknowledgment_phrases = [
    'i see', 'isee', 'okay', 'ok', 'oke', 'ok then', 
    'got it', 'cool', 'ah okay', 'i understand', 'makes sense',
    'alright', 'right', 'yes', 'yep', 'yeah', 'sure', 'of course',
    'noted', 'roger', 'acknowledged', 'understood'
]

career_keywords = {
    "web developer": r"web.*(dev|develop|engine|program)|website.*(dev|develop|engine|program)|full.?stack",
    "frontend developer": r"front.?end.*(dev|develop|engine)|ui.*(dev|develop|engine)|user.?interface.*(dev|develop|engine)|client.?side.*(dev|develop|engine)",
    "backend developer": r"back.?end.*(dev|develop|engine)|server.?side.*(dev|develop|engine)|api.*(dev|develop|engine)",
    "data scientist": r"data scien|data analy|machine learning scien|ml scien",
    "devops engineer": r"devops|sre|site reliability|cloud engineer|infrastructure engineer|ci.?cd",
    "mobile developer": r"mobile.*(dev|develop|engine)|app.*(dev|develop|program)|ios.*(dev|develop)|android.*(dev|develop)",
    "ui ux designer": r"ui.*design|ux.*design|user.*experience|user.?interface|wirefram|prototyp",
    ".net developer": r"\.net.*(dev|develop|engine)|c#.*(dev|develop|program)|c sharp.*(dev|develop)",
    "machine learning engineer": r"ml engineer|machine learning engineer|mle",
    "python developer": r"python.*(dev|develop|engine|program)",
    "java developer": r"java.*(dev|develop|engine|program)",
    "cybersecurity specialist": r"cyber.?security|infosec|security analy|ethical hack|penetration test|pen.?test|hack|hacker",
    "data analyst": r"data analy|business intelligence|bi analy|reporting",
    "data engineer": r"data engin|etl|data pipeline|data warehous|data infra",
    "game developer": r"game.*(dev|develop|program)|unity|unreal|gaming",
    "cloud engineer": r"cloud.*(engin|architect)|aws|azure|gcp|google cloud",
    "systems engineer": r"systems.*(engin|admin)|sysadmin|linux admin",
    "enterprise developer": r"enterprise.*(dev|develop)|java ee|j2ee",
    "android developer": r"android.*(dev|develop)|kotlin.*mobile",
    "ios developer": r"ios.*(dev|develop)|swift.*dev|apple.*dev",
    "business intelligence analyst": r"business intelligence|bi.*analy|power bi|tableau",
    "security analyst": r"security analy|soc analy|incident response",
    "database administrator": r"database admin|dba|sql.*admin",
    "automation engineer": r"automation.*(engin|test)|qa automation|selenium",
    "site reliability engineer (sre)": r"sre|site reliability|reliability engin",
    "blockchain developer": r"blockchain|web3|solidity|smart contract",
    "wordpress developer": r"wordpress|wp.*(dev|develop)",
    "macos developer": r"macos|mac.*os.*(dev|develop)|desktop.*app",
    "web designer": r"web.*design|html.*css|frontend design",
    "ui developer": r"ui.*dev|interface.*dev|component.*dev",
    "email developer": r"email.*dev|html.*email|newsletter.*dev",
    "react developer": r"react.*dev|reactjs|react\.js",
    "api developer": r"api.*dev|rest.*api|graphql",
    "solutions architect": r"solutions.*architect|cloud.*architect",
    "ai developer": r"ai.*dev|artificial intelligence|nlp|natural language",
    "computer vision engineer": r"computer vision|cv.*engin|opencv",
    "data visualisation specialist": r"data visual|viz|tableau|powerbi|looker",
    "ethical hacker": r"ethical hack|white hat|penetration test",
    "penetration tester": r"penetration test|pen.?test|pentest",
    "incident responder": r"incident response|digital forensics",
    "security engineer": r"security engin|devsecops|appsec",
    "product designer": r"product design|ux design|user experience",
    "statistician": r"statistician|stats|mathematical stat",
    "quantitative analyst": r"quantitative|quant|financial model"
}

tech_to_career = {
    "python": ["Data Scientist", "Backend Developer", "Machine Learning Engineer", "Python Developer", "Data Analyst", "Automation Engineer"],
    "javascript": ["Frontend Developer", "Fullstack Developer", "Web Developer", "JavaScript Developer", "UI Engineer"],
    "typescript": ["Frontend Developer", "Fullstack Developer", "Node.js Developer"],
    "java": ["Enterprise Developer", "Android Developer", "Backend Engineer", "Java Developer", "Cloud Engineer"],
    "c#": ["Game Developer", ".NET Developer", "Windows Application Developer", "Backend Developer"],
    "go": ["Backend Developer", "Cloud Engineer", "Site Reliability Engineer (SRE)"],
    "rust": ["Systems Engineer", "Backend Developer", "Blockchain Developer"],
    "php": ["Backend Developer", "WordPress Developer", "Fullstack Developer"],
    "swift": ["iOS Developer", "macOS Developer"],
    "kotlin": ["Android Developer", "Backend Developer"],
    "linux": ["DevOps Engineer", "System Administrator", "Cloud Engineer", "Site Reliability Engineer (SRE)"],
    "html": ["Frontend Developer", "Web Designer", "UI Developer", "Email Developer"],
    "css": ["Frontend Developer", "Web Designer", "UI Developer"],
    "react": ["Frontend Developer", "React Developer", "UI Engineer", "Fullstack Developer"],
    "node": ["Backend Developer", "Fullstack Developer", "API Developer", "Node.js Developer"],
    "sql": ["Database Administrator", "Data Analyst", "Data Engineer", "Backend Developer", "Business Intelligence Analyst"],
    "aws": ["DevOps Engineer", "Cloud Architect", "Cloud Engineer", "Solutions Architect", "SRE"],
    "azure": ["DevOps Engineer", "Cloud Architect", "Cloud Engineer", "Solutions Architect"],
    "gcp": ["DevOps Engineer", "Cloud Architect", "Cloud Engineer", "Data Engineer"],
    "docker": ["DevOps Engineer", "Site Reliability Engineer (SRE)", "Backend Developer", "Cloud Engineer"],
    "kubernetes": ["DevOps Engineer", "Site Reliability Engineer (SRE)", "Cloud Engineer"],
    "terraform": ["DevOps Engineer", "Cloud Engineer", "Infrastructure Engineer"],
    "machine learning": ["Data Scientist", "ML Engineer", "AI Developer", "Machine Learning Specialist", "Computer Vision Engineer"],
    "tableau": ["Data Analyst", "Business Intelligence Analyst", "Data Visualisation Specialist"],
    "power bi": ["Data Analyst", "Business Intelligence Analyst", "Data Visualisation Specialist"],
    "cybersecurity": ["Security Analyst", "Ethical Hacker", "Penetration Tester", "Incident Responder", "Security Engineer"],
    "figma": ["UI/UX Designer", "Product Designer", "Web Designer"],
    "r": ["Data Scientist", "Data Analyst", "Statistician", "Quantitative Analyst"],
    "c++": ["Game Developer", "Systems Engineer", "Embedded Systems Developer"],
    "ruby": ["Backend Developer", "Fullstack Developer", "Ruby on Rails Developer"],
    "vue": ["Frontend Developer", "Vue.js Developer", "Fullstack Developer"],
    "angular": ["Frontend Developer", "Angular Developer", "Fullstack Developer"],
    "svelte": ["Frontend Developer", "JavaScript Developer", "UI Engineer"],
    "flutter": ["Mobile Developer", "Frontend Developer", "Cross-platform Developer"],
    "dart": ["Mobile Developer", "Flutter Developer"],
    "scala": ["Data Engineer", "Backend Developer", "Big Data Engineer"],
    "hadoop": ["Data Engineer", "Big Data Engineer", "Data Architect"],
    "spark": ["Data Engineer", "Big Data Engineer", "Data Scientist"],
    "kafka": ["Data Engineer", "Backend Developer", "Streaming Engineer"],
    "elasticsearch": ["Data Engineer", "Backend Developer", "Search Engineer"],
    "mongodb": ["Backend Developer", "Fullstack Developer", "Database Administrator"],
    "postgresql": ["Backend Developer", "Database Administrator", "Data Engineer"],
    "mysql": ["Backend Developer", "Database Administrator", "Web Developer"],
    "redis": ["Backend Developer", "DevOps Engineer", "Cache Specialist"],
    "jenkins": ["DevOps Engineer", "CI/CD Engineer", "Automation Engineer"],
    "ansible": ["DevOps Engineer", "Infrastructure Engineer", "Automation Engineer"],
    "puppet": ["DevOps Engineer", "Infrastructure Engineer", "System Administrator"],
    "chef": ["DevOps Engineer", "Infrastructure Engineer", "Automation Engineer"],
    "graphql": ["Backend Developer", "Fullstack Developer", "API Developer"],
    "rest": ["Backend Developer", "API Developer", "Fullstack Developer"],
    "redux": ["Frontend Developer", "React Developer", "JavaScript Developer"],
    "sass": ["Frontend Developer", "Web Designer", "UI Developer"],
    "less": ["Frontend Developer", "Web Designer", "UI Developer"],
    "tailwind": ["Frontend Developer", "Web Designer", "UI Developer"],
    "bootstrap": ["Frontend Developer", "Web Designer", "UI Developer"],
    "firebase": ["Backend Developer", "Mobile Developer", "Fullstack Developer"],
    "serverless": ["Backend Developer", "Cloud Engineer", "DevOps Engineer"],
    "lambda": ["Backend Developer", "Cloud Engineer", "Serverless Developer"],
    "electron": ["Desktop Developer", "JavaScript Developer", "Fullstack Developer"],
    "xamarin": ["Mobile Developer", "Cross-platform Developer", ".NET Developer"],
    "react native": ["Mobile Developer", "JavaScript Developer", "Cross-platform Developer"],
    "ionic": ["Mobile Developer", "Frontend Developer", "Hybrid App Developer"],
    "unity": ["Game Developer", "AR/VR Developer", "3D Developer"],
    "unreal": ["Game Developer", "AR/VR Developer", "3D Developer"],
    "blender": ["Game Developer", "3D Artist", "UI/UX Designer"],
    "sketch": ["UI/UX Designer", "Product Designer", "Web Designer"],
    "adobe xd": ["UI/UX Designer", "Product Designer", "Web Designer"],
    "zeplin": ["UI/UX Designer", "Product Designer", "Frontend Developer"],
    "invision": ["UI/UX Designer", "Product Designer", "Prototype Designer"],
    "jira": ["Project Manager", "Scrum Master", "Product Owner"],
    "confluence": ["Technical Writer", "Project Manager", "Business Analyst"],
    "trello": ["Project Manager", "Product Owner", "Scrum Master"],
    "asana": ["Project Manager", "Product Owner", "Team Lead"],
    "slack": ["Business Analyst", "Project Manager", "Team Collaborator"],
    "microsoft teams": ["Business Analyst", "Project Manager", "Team Collaborator"],
    "git": ["Software Developer", "DevOps Engineer", "Technical Lead"],
    "github": ["Software Developer", "Open Source Contributor", "DevOps Engineer"],
    "gitlab": ["Software Developer", "DevOps Engineer", "CI/CD Engineer"],
    "bitbucket": ["Software Developer", "DevOps Engineer", "Project Manager"],
    "vscode": ["Software Developer", "Programmer", "Coder"],
    "intellij": ["Java Developer", "Software Developer", "Programmer"],
    "eclipse": ["Java Developer", "Enterprise Developer", "Software Developer"],
    "xcode": ["iOS Developer", "macOS Developer", "Apple Developer"],
    "android studio": ["Android Developer", "Mobile Developer", "Kotlin Developer"],
    "postman": ["API Developer", "Backend Developer", "QA Engineer"],
    "swagger": ["API Developer", "Backend Developer", "Technical Writer"],
    "selenium": ["Automation Engineer", "QA Engineer", "Test Engineer"],
    "jest": ["JavaScript Developer", "Frontend Developer", "Test Engineer"],
    "mocha": ["JavaScript Developer", "Backend Developer", "Test Engineer"],
    "junit": ["Java Developer", "Test Engineer", "Automation Engineer"],
    "pytest": ["Python Developer", "Test Engineer", "Automation Engineer"],
    "cypress": ["Frontend Developer", "Test Engineer", "QA Engineer"],
    "jenkins": ["DevOps Engineer", "CI/CD Engineer", "Automation Engineer"],
    "travis ci": ["DevOps Engineer", "CI/CD Engineer", "Open Source Developer"],
    "circleci": ["DevOps Engineer", "CI/CD Engineer", "Automation Engineer"],
    "github actions": ["DevOps Engineer", "CI/CD Engineer", "Open Source Developer"],
    "datadog": ["DevOps Engineer", "SRE", "Performance Engineer"],
    "new relic": ["DevOps Engineer", "SRE", "Performance Engineer"],
    "splunk": ["DevOps Engineer", "Security Analyst", "Data Analyst"],
    "prometheus": ["DevOps Engineer", "SRE", "Cloud Engineer"],
    "grafana": ["DevOps Engineer", "SRE", "Data Visualisation Specialist"],
    "nginx": ["DevOps Engineer", "Backend Developer", "System Administrator"],
    "apache": ["DevOps Engineer", "System Administrator", "Backend Developer"]
}

career_to_tech = {
    "web developer": ["HTML", "CSS", "JavaScript", "Git", "APIs (REST, GraphQL)", "Browser DevTools"],
    "frontend developer": ["HTML", "CSS", "JavaScript", "TypeScript", "React / Vue / Angular", "Git", "Package Managers (NPM/Yarn)"],
    "backend developer": ["Python / Java / Go / Node.js", "SQL / NoSQL Databases", "Docker", "Kubernetes", "Cloud (AWS/Azure/GCP)", "Git", "CI/CD"],
    "fullstack developer": ["Frontend Skills", "Backend Skills", "Databases", "Git", "Cloud Deployment"],
    "data scientist": ["Python (Pandas, NumPy)", "SQL", "Machine Learning (Scikit-learn)", "Deep Learning (TensorFlow/PyTorch)", "Data Visualization (Tableau/Power BI)", "Statistics", "Git"],
    "devops engineer": ["Linux", "Cloud (AWS/Azure/GCP)", "Docker", "Kubernetes", "Terraform / IaC", "CI/CD (Jenkins, GitLab CI)", "Scripting (Bash/Python)"],
    "cloud engineer": ["Cloud (AWS/Azure/GCP)", "Terraform / IaC", "Docker", "Kubernetes", "Networking", "Linux", "Security Principles"],
    "mobile developer": ["Swift (iOS) / Kotlin (Android)", "Xcode / Android Studio", "Git", "API Integration", "Firebase"],
    "ui ux designer": ["Figma / Sketch / Adobe XD", "Wireframing", "Prototyping", "User Research", "User Testing", "Design Systems"],
    ".net developer": ["C#", ".NET Framework", "ASP.NET", "SQL Server", "Azure", "Git"],
    "cybersecurity specialist": ["Networking (TCP/IP)", "Linux", "Python Scripting", "Penetration Testing Tools (Metasploit, Burp Suite)", "Cryptography", "Security Frameworks (NIST)"],
    "data analyst": ["SQL", "Excel", "Python (Pandas)", "Tableau / Power BI", "Statistics", "Communication Skills"],
    "data engineer": ["Python / Scala / Java", "Advanced SQL", "Apache Spark", "Data Warehousing (Snowflake, BigQuery)", "ETL/ELT Processes", "Airflow"],
    "game developer": ["C++ / C#", "Unity / Unreal Engine", "Linear Algebra & Physics", "3D Modeling Software (Blender)", "Git"],
    "machine learning engineer": ["Python", "TensorFlow / PyTorch", "Docker", "Kubernetes", "Cloud ML Platforms (SageMaker/Vertex AI)", "MLOps Principles"],
    "enterprise developer": ["Java EE", "Spring Framework", "SQL Databases", "Microservices", "Cloud Platforms", "Security Protocols"],
    "android developer": ["Kotlin / Java", "Android SDK", "Android Studio", "XML", "Firebase", "RESTful APIs"],
    "backend engineer": ["Server-side Language (Java/Python/Go)", "Database Systems", "API Design", "Cloud Infrastructure", "Caching Strategies", "Security"],
    "java developer": ["Java", "Spring Boot", "Hibernate", "Maven/Gradle", "JUnit", "Microservices"],
    "system administrator": ["Linux/Windows OS", "Networking", "Scripting (Bash/PowerShell)", "Virtualization", "Monitoring Tools", "Security Basics"],
    "cloud architect": ["Cloud Platforms (AWS/Azure/GCP)", "Infrastructure as Code", "Networking", "Security", "System Design", "Cost Optimization"],
    "security analyst": ["SIEM Tools", "Network Protocols", "Incident Response", "Threat Intelligence", "Security Frameworks", "Forensic Tools"],
    "database administrator": ["SQL", "Database Systems (Oracle/MySQL/PostgreSQL)", "Backup & Recovery", "Performance Tuning", "Security", "High Availability"],
    "python developer": ["Python", "Web Frameworks (Django/Flask)", "API Development", "Database Integration", "Testing (Pytest)", "Deployment"],
    "automation engineer": ["Python/Java", "Selenium", "Testing Frameworks", "CI/CD Pipelines", "API Testing", "Performance Testing"],
    "javascript developer": ["JavaScript", "Node.js", "Frontend Frameworks", "API Development", "Build Tools (Webpack)", "Testing (Jest/Mocha)"],
    "ui engineer": ["HTML/CSS", "JavaScript", "UI Frameworks (React/Vue)", "Design Systems", "Accessibility", "Performance Optimization"],
    "node.js developer": ["JavaScript", "Node.js", "Express.js", "REST/GraphQL APIs", "Database Integration", "Testing"],
    "windows application developer": ["C#", ".NET", "WPF/UWP", "Visual Studio", "SQL Server", "Windows APIs"],
    "site reliability engineer (sre)": ["Linux", "Scripting", "Monitoring Tools", "Incident Response", "Capacity Planning", "Automation"],
    "systems engineer": ["Operating Systems", "Networking", "Scripting", "Virtualization", "Hardware Knowledge", "Troubleshooting"],
    "blockchain developer": ["Solidity", "Ethereum", "Smart Contracts", "Web3.js", "Cryptography", "Distributed Systems"],
    "wordpress developer": ["PHP", "WordPress", "HTML/CSS", "JavaScript", "MySQL", "Theme/Plugin Development"],
    "ios developer": ["Swift", "Xcode", "UIKit/SwiftUI", "CocoaPods", "Core Data", "REST APIs"],
    "macos developer": ["Swift", "Xcode", "AppKit", "Cocoa", "Objective-C", "Mac APIs"],
    "web designer": ["HTML/CSS", "JavaScript", "Design Tools (Figma/Photoshop)", "Responsive Design", "Typography", "Color Theory"],
    "ui developer": ["HTML/CSS", "JavaScript", "UI Frameworks", "Design Systems", "Responsive Design", "Browser Compatibility"],
    "email developer": ["HTML/CSS", "Email Marketing Platforms", "Responsive Design", "Email Client Compatibility", "Accessibility", "Testing Tools"],
    "react developer": ["JavaScript", "React", "State Management (Redux)", "HTML/CSS", "REST APIs", "Testing (Jest/Enzyme)"],
    "api developer": ["API Design", "REST/GraphQL", "Authentication (OAuth/JWT)", "API Documentation", "Testing", "Performance Optimization"],
    "business intelligence analyst": ["SQL", "BI Tools (Tableau/Power BI)", "Data Modeling", "Excel", "Statistics", "Data Visualization"],
    "infrastructure engineer": ["Cloud Platforms", "Infrastructure as Code", "Networking", "Security", "Scripting", "Monitoring"],
    "solutions architect": ["System Design", "Cloud Architecture", "Integration Patterns", "Security", "Cost Optimization", "Technical Leadership"],
    "ml engineer": ["Python", "Machine Learning Frameworks", "Data Processing", "Model Deployment", "MLOps", "Cloud ML Services"],
    "ai developer": ["Python", "AI Algorithms", "Natural Language Processing", "Neural Networks", "Data Structures", "Cloud AI Services"],
    "machine learning specialist": ["Machine Learning Algorithms", "Statistical Modeling", "Data Preprocessing", "Feature Engineering", "Model Evaluation", "Research Skills"],
    "computer vision engineer": ["Python", "OpenCV", "Deep Learning", "Image Processing", "Neural Networks", "GPU Programming"],
    "data visualisation specialist": ["Data Visualization Tools", "Design Principles", "Statistics", "JavaScript (D3.js)", "Dashboard Design", "Storytelling"],
    "ethical hacker": ["Penetration Testing", "Vulnerability Assessment", "Network Security", "Cryptography", "Social Engineering", "Security Tools"],
    "penetration tester": ["Penetration Testing Methodologies", "Security Tools", "Network Protocols", "Web Application Security", "Reporting", "Ethical Guidelines"],
    "incident responder": ["Incident Response Procedures", "Forensic Tools", "Malware Analysis", "Threat Intelligence", "Communication Skills", "Documentation"],
    "security engineer": ["Security Architecture", "Cryptography", "Network Security", "Application Security", "Security Protocols", "Risk Assessment"],
    "product designer": ["User Research", "Wireframing", "Prototyping", "UI Design", "UX Principles", "Design Tools"],
    "statistician": ["Statistical Methods", "R/Python", "Data Analysis", "Experimental Design", "Probability Theory", "Statistical Software"],
    "quantitative analyst": ["Mathematical Modeling", "Statistics", "Programming (Python/R)", "Financial Knowledge", "Algorithm Development", "Data Analysis"]
}